using Microsoft.EntityFrameworkCore.Metadata.Builders;
using CleanArchitecture.Domain.Common;

namespace CleanArchitecture.Infrastructure.IdGeneration;

public static class StringIdEntityTypeBuilderExtensions
{
    /// <summary>
    /// Width of a generated id column. A radical of a few characters plus a separator and a
    /// six-digit counter leaves plenty of room, and the ceiling keeps the key narrow enough to
    /// index well.
    /// </summary>
    public const int DefaultIdMaxLength = 32;

    /// <summary>
    /// Configures a string primary key generated by <see cref="StringHiLoIdGenerator"/>.
    /// <para>
    /// Call this from the entity's <c>IEntityTypeConfiguration</c> for every entity passed to
    /// <c>RegisterStringId&lt;TEntity&gt;</c>; the two go together. The registration says which
    /// radical to use, this says how EF should hold the key until the interceptor assigns it.
    /// </para>
    /// </summary>
    public static EntityTypeBuilder<TEntity> HasGeneratedStringId<TEntity>(
        this EntityTypeBuilder<TEntity> builder,
        int maxLength = DefaultIdMaxLength)
        where TEntity : BaseEntity<string>
    {
        builder.Property(e => e.Id)
            .ValueGeneratedOnAdd()
            .HasValueGenerator<TemporaryStringIdValueGenerator>()
            .HasMaxLength(maxLength)
            .IsRequired();

        return builder;
    }
}
