using Microsoft.AspNetCore.OpenApi;
using Microsoft.OpenApi;

namespace CleanArchitecture.Web.Infrastructure;
/// <summary>
/// Adds human-readable summaries and descriptions to the ASP.NET Core Identity endpoints
/// registered by <c>MapIdentityApi</c> (nested under <c>api/Users/identity/*</c>). Those endpoints
/// are generated by the framework and cannot be annotated with <see cref="EndpointSummaryAttribute"/>
/// or <see cref="EndpointDescriptionAttribute"/> directly, so metadata is applied here by matching on
/// the operation's relative path (and HTTP method for ambiguous paths). The canonical
/// <c>register</c>/<c>login</c> endpoints are custom and annotated directly, so they are not listed here.
/// </summary>
internal sealed class IdentityApiOperationTransformer : IOpenApiOperationTransformer
{
    private static readonly Dictionary<string, (string Summary, string Description)> _metadata = new()
    {
        ["api/Users/identity/register"] = ("Register (Identity)", "Creates a new user account via the built-in Identity API."),
        ["api/Users/identity/login"] = ("Log in (Identity)", "Authenticates a user. Use ?useCookies=true for cookie-based authentication."),
        ["api/Users/identity/refresh"] = ("Refresh token", "Returns a new access token using a valid refresh token."),
        ["api/Users/identity/confirmEmail"] = ("Confirm email", "Confirms a user's email address using the token sent by email."),
        ["api/Users/identity/resendConfirmationEmail"] = ("Resend confirmation email", "Sends a new email confirmation link to the specified address."),
        ["api/Users/identity/forgotPassword"] = ("Forgot password", "Sends a password reset link to the specified email address."),
        ["api/Users/identity/resetPassword"] = ("Reset password", "Resets a user's password using the token sent by email."),
        ["api/Users/identity/manage/2fa"] = ("Manage two-factor authentication", "Enables, disables, or retrieves two-factor authentication settings."),
        ["api/Users/identity/manage/info GET"] = ("Get account info", "Returns the current user's email and two-factor authentication status."),
        ["api/Users/identity/manage/info POST"] = ("Update account info", "Updates the current user's email or password."),
    };

    public Task TransformAsync(OpenApiOperation operation, OpenApiOperationTransformerContext context, CancellationToken cancellationToken)
    {
        var path = context.Description.RelativePath ?? "";
        var key = $"{path} {context.Description.HttpMethod?.ToUpperInvariant()}";

        if (_metadata.TryGetValue(key, out var meta) || _metadata.TryGetValue(path, out meta))
        {
            operation.Summary = meta.Summary;
            operation.Description = meta.Description;
        }

        return Task.CompletedTask;
    }
}