<Project Sdk="Aspire.AppHost.Sdk/13.4.6">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>CleanArchitecture.TestAppHost</RootNamespace>
    <AssemblyName>CleanArchitecture.TestAppHost</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.PostgreSQL" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Shared\Shared.csproj" IsAspireProjectResource="false" />
  </ItemGroup>

</Project>
